"""CXSentinel PDF report builder.

Produces a professionally formatted analysis report (fpdf2 + matplotlib):
title block, executive summary, key-metrics table, numbered figures
(sentiment distribution, confidence, trend, aspects, emotions), numbered
tables (aspects, channels, segments, urgent queue), business insights,
recommendations and a methodology note.
"""

from datetime import datetime
from io import BytesIO

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
from fpdf import FPDF
from fpdf.fonts import FontFace

BRAND = (82, 39, 255)          # #5227FF
DARK = (30, 24, 54)
GREY = (110, 105, 130)
SENT_COLORS = {"Positive": "#2eb086", "Negative": "#e05656", "Neutral": "#e8b93e"}

APP_NAME = "CXSentinel"


def _s(text) -> str:
    """Sanitise text for the PDF's latin-1 core fonts."""
    text = str(text).replace("**", "")
    for a, b in [("—", "-"), ("–", "-"), ("‘", "'"), ("’", "'"),
                 ("“", '"'), ("”", '"'), ("…", "..."), ("·", "-"),
                 ("→", "->"), ("≥", ">="), ("≤", "<=")]:
        text = text.replace(a, b)
    return text.encode("latin-1", "replace").decode("latin-1")


def _fig_bytes(fig) -> BytesIO:
    buf = BytesIO()
    fig.savefig(buf, format="png", dpi=150, bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    buf.seek(0)
    return buf


class ReportPDF(FPDF):
    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*BRAND)
        self.cell(0, 6, f"{APP_NAME} - Customer Feedback Analysis Report",
                  align="L")
        self.set_draw_color(*BRAND)
        self.line(10, 16, 200, 16)
        self.ln(10)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*GREY)
        self.cell(0, 8, f"Page {self.page_no()} | Generated By {APP_NAME}",
                  align="C")

    # ---- building blocks ----
    def h1(self, text):
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(*BRAND)
        self.cell(0, 9, _s(text), new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def body(self, text, size=10):
        self.set_font("Helvetica", "", size)
        self.set_text_color(*DARK)
        self.multi_cell(0, 5.2, _s(text))
        self.ln(1)

    def caption(self, text):
        self.set_font("Helvetica", "BI", 9)
        self.set_text_color(*GREY)
        self.multi_cell(0, 5, _s(text))
        self.ln(2)

    def add_figure(self, fig, number, title, width=150):
        buf = _fig_bytes(fig)
        if self.get_y() > 200:
            self.add_page()
        x = (210 - width) / 2
        self.image(buf, x=x, w=width)
        self.set_x(10)
        self.caption(f"Figure {number}: {title}")

    def add_table(self, number, title, headers, rows, col_widths=None):
        if self.get_y() > 230:
            self.add_page()
        self.caption(f"Table {number}: {title}")
        self.set_font("Helvetica", "", 8.5)
        self.set_text_color(*DARK)
        self.set_draw_color(200, 195, 220)
        heading_face = FontFace(emphasis="BOLD", color=DARK,
                                fill_color=(238, 234, 250))
        with self.table(col_widths=col_widths, borders_layout="SINGLE_TOP_LINE",
                        line_height=5.5, text_align="LEFT",
                        headings_style=heading_face) as table:
            head = table.row()
            for h in headers:
                head.cell(_s(h))
            for r in rows:
                row = table.row()
                for cell in r:
                    row.cell(_s(cell))
        self.ln(4)


def _net(group: pd.Series) -> float:
    return 100 * ((group == "Positive").mean() - (group == "Negative").mean())


def build_pdf(results: pd.DataFrame, summary: str, insights: list, recs: list,
              aspects: pd.DataFrame, review_threshold: float,
              batch_name: str = "Uploaded Dataset") -> bytes:
    pct = {s: 100 * (results["sentiment"] == s).mean()
           for s in ("Positive", "Neutral", "Negative")}
    net = pct["Positive"] - pct["Negative"]
    avg_conf = results["confidence"].mean()
    urgent_n = int((results.get("risk", pd.Series(dtype=str)) == "High").sum())
    review_n = int((results["confidence"] < review_threshold).sum())
    fig_n = 0
    tbl_n = 0

    pdf = ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # ---------------- Title block ----------------
    pdf.set_font("Helvetica", "B", 26)
    pdf.set_text_color(*BRAND)
    pdf.cell(0, 14, APP_NAME, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*DARK)
    pdf.cell(0, 9, "Customer Feedback Analysis Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*GREY)
    pdf.cell(0, 6, _s(f"Dataset: {batch_name}  |  Generated: "
                      f"{datetime.now().strftime('%d %B %Y, %H:%M')}"),
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(*BRAND)
    pdf.set_line_width(0.6)
    pdf.line(10, pdf.get_y() + 2, 200, pdf.get_y() + 2)
    pdf.ln(8)

    # ---------------- 1. Executive summary ----------------
    pdf.h1("1. Executive Summary")
    pdf.body(summary)
    pdf.ln(2)

    tbl_n += 1
    pdf.add_table(
        tbl_n, "Key Metrics",
        ["Metric", "Value"],
        [["Total Feedback Volume", f"{len(results):,} items"],
         ["Positive / Neutral / Negative",
          f"{pct['Positive']:.0f}% / {pct['Neutral']:.0f}% / {pct['Negative']:.0f}%"],
         ["Net Sentiment Score (NSS)", f"{net:+.0f}  (range -100 to +100)"],
         ["Average CSAT Equivalent",
          f"{results['csat'].mean():.2f} / 5" if "csat" in results.columns else "n/a"],
         ["Average Model Confidence", f"{avg_conf:.0%}"],
         ["AI Confidence Weighting (Review Threshold)", f"{review_threshold:.0%}"],
         ["Items Needing Human Review", f"{review_n:,}"],
         ["Urgent (High-Risk) Items", f"{urgent_n:,}"]],
        col_widths=(95, 85))

    # ---------------- 2. Sentiment overview ----------------
    pdf.h1("2. Sentiment Overview")
    counts = results["sentiment"].value_counts()
    fig, ax = plt.subplots(figsize=(4.6, 3.2))
    ax.pie(counts.values, labels=counts.index, autopct="%1.0f%%", startangle=110,
           colors=[SENT_COLORS[s] for s in counts.index],
           textprops={"fontsize": 10})
    ax.set_title("Sentiment Distribution", fontsize=11)
    fig_n += 1
    pdf.add_figure(fig, fig_n, "Distribution Of Sentiment Across The Dataset",
                   width=105)

    fig, ax = plt.subplots(figsize=(5.6, 2.6))
    for s in ("Positive", "Neutral", "Negative"):
        subset = results.loc[results["sentiment"] == s, "confidence"]
        if len(subset):
            ax.hist(subset, bins=15, range=(0.3, 1.0), alpha=0.65,
                    label=s, color=SENT_COLORS[s])
    ax.axvline(review_threshold, color="#5227FF", linestyle="--", linewidth=1.2,
               label=f"Review Threshold ({review_threshold:.0%})")
    ax.set_xlabel("Model Confidence")
    ax.set_ylabel("Items")
    ax.legend(fontsize=8)
    fig_n += 1
    pdf.add_figure(fig, fig_n, "Model Confidence By Sentiment, With The AI "
                               "Confidence Weighting Marked", width=150)

    # ---------------- 3. Trends (if timestamps present) ----------------
    if "created_at" in results.columns:
        valid = results.dropna(subset=["created_at"])
        if len(valid) >= 5:
            pdf.h1("3. Volume & Sentiment Over Time")
            span_days = (valid["created_at"].max() - valid["created_at"].min()).days
            freq = "D" if span_days >= 3 else "h"
            trend = (valid.groupby([pd.Grouper(key="created_at", freq=freq),
                                    "sentiment"]).size().unstack(fill_value=0))
            fig, ax = plt.subplots(figsize=(6.2, 2.8))
            cols = [c for c in ("Positive", "Neutral", "Negative") if c in trend.columns]
            ax.stackplot(trend.index, [trend[c] for c in cols], labels=cols,
                         colors=[SENT_COLORS[c] for c in cols], alpha=0.85)
            ax.set_ylabel("Feedback Items")
            ax.legend(fontsize=8, loc="upper left")
            fig.autofmt_xdate()
            fig_n += 1
            pdf.add_figure(fig, fig_n, "Feedback Volume Over Time, Stacked By "
                                       "Sentiment", width=165)

    # ---------------- 4. Aspects, channels & segments ----------------
    pdf.h1("4. Aspect, Channel & Segment Analysis")
    if aspects is not None and not aspects.empty:
        pivot = aspects.pivot_table(index="aspect", columns="sentiment",
                                    values="count", fill_value=0)
        fig, ax = plt.subplots(figsize=(5.8, 3.0))
        pivot.plot(kind="barh", ax=ax,
                   color=[SENT_COLORS.get(c, "#888") for c in pivot.columns])
        ax.set_xlabel("Feedback Items")
        ax.set_ylabel("")
        ax.legend(fontsize=8)
        fig_n += 1
        pdf.add_figure(fig, fig_n, "Feedback Volume Per Business Aspect, "
                                   "Split By Sentiment", width=155)
        tbl_n += 1
        pdf.add_table(
            tbl_n, "Business Aspects Mentioned In Feedback",
            ["Aspect"] + list(pivot.columns),
            [[a] + [str(int(v)) for v in row] for a, row in pivot.iterrows()])
    else:
        pdf.body("No recognisable business aspects were detected in this dataset.")

    if "channel" in results.columns and results["channel"].nunique() > 1:
        by_ch = (results.groupby("channel")
                 .agg(items=("sentiment", "size"), net=("sentiment", _net))
                 .sort_values("items", ascending=False).head(12))
        tbl_n += 1
        pdf.add_table(
            tbl_n, "Sentiment By Channel",
            ["Channel", "Items", "Net Sentiment"],
            [[ch, str(int(r["items"])), f"{r['net']:+.0f}"]
             for ch, r in by_ch.iterrows()],
            col_widths=(90, 40, 50))

    if "segment" in results.columns and results["segment"].nunique() > 1:
        by_seg = (results.groupby("segment")
                  .agg(items=("sentiment", "size"), net=("sentiment", _net))
                  .sort_values("items", ascending=False).head(12))
        tbl_n += 1
        pdf.add_table(
            tbl_n, "Sentiment By Customer Segment / Location",
            ["Segment", "Items", "Net Sentiment"],
            [[seg, str(int(r["items"])), f"{r['net']:+.0f}"]
             for seg, r in by_seg.iterrows()],
            col_widths=(90, 40, 50))

    # ---------------- 5. Emotions & risk ----------------
    if "emotion" in results.columns:
        pdf.h1("5. Emotional Intensity & Risk")
        emo = (results.groupby(["emotion", "sentiment"]).size()
               .unstack(fill_value=0))
        fig, ax = plt.subplots(figsize=(5.6, 2.8))
        emo.plot(kind="barh", ax=ax,
                 color=[SENT_COLORS.get(c, "#888") for c in emo.columns])
        ax.set_xlabel("Items")
        ax.set_ylabel("")
        ax.legend(fontsize=8)
        fig_n += 1
        pdf.add_figure(fig, fig_n, "Primary Emotions Detected (AI-Scored "
                                   "Intensity Blends Model Confidence With "
                                   "Lexical Signals)", width=150)

        urgent = results[results["risk"] == "High"].nlargest(10, "intensity")
        if not urgent.empty:
            tbl_n += 1
            pdf.add_table(
                tbl_n, "Urgent Response Queue - High-Risk Items (Respond First)",
                ["Feedback (Truncated)", "Emotion", "Intensity", "Confidence"],
                [[r.text[:80] + ("..." if len(r.text) > 80 else ""),
                  r.emotion, f"{r.intensity}/100", f"{r.confidence:.0%}"]
                 for r in urgent.itertuples()],
                col_widths=(100, 30, 25, 25))

    # ---------------- 6. Business insights ----------------
    pdf.add_page()
    pdf.h1("6. Business Insights")
    for line in insights:
        pdf.body(f"-  {line}", size=10)
    pdf.ln(2)

    # ---------------- 7. Recommendations ----------------
    pdf.h1("7. Recommendations")
    for i, line in enumerate(recs, 1):
        pdf.body(f"{i}.  {line}", size=10)
    pdf.ln(2)

    # ---------------- 8. Methodology ----------------
    pdf.h1("8. Methodology")
    pdf.body(
        "Sentiment classification uses a DistilBERT transformer fine-tuned on "
        "28,096 real labelled texts (tweets plus Amazon and Yelp customer "
        "reviews), achieving 73.3% accuracy / 0.728 macro F1 on held-out "
        "customer reviews and 67.6% on tweets. Each item receives Positive / "
        "Neutral / Negative probabilities; emotional intensity (0-100) blends "
        "model confidence with emotion-lexicon signals, intensifiers and "
        "punctuation emphasis. Business aspects are detected via keyword "
        "lexicons per area. Items with model confidence below the AI "
        f"Confidence Weighting ({review_threshold:.0%}) are routed to human "
        "review rather than automated handling. Net Sentiment Score = "
        "%Positive - %Negative. CSAT equivalent maps sentiment and confidence "
        "onto a 1-5 satisfaction scale.")

    return bytes(pdf.output())
